"""initial migration

Revision ID: 90b314aa1b48
Revises: 
Create Date: 2024-10-28 05:30:48.914383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '90b314aa1b48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_info',
    sa.Column('key_code', sa.String(length=50), nullable=False, comment='環境情報のキーコード'),
    sa.Column('values', sa.String(length=255), nullable=False, comment='環境情報の値'),
    sa.Column('created_by', sa.String(length=50), nullable=False, comment='レコードの登録者'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='レコードの更新者'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='レコードの登録日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='レコードの更新日時'),
    sa.PrimaryKeyConstraint('key_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environment_info')
    # ### end Alembic commands ###
