services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    working_dir: '/app/'
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      PYTHONPYCACHEPREFIX: "/dev/null"  # __pycache__の生成を無効化
    env_file:
      - .env.prod
    volumes:
      - ./backend/src:/app
      - ./logs/backend:/logs
