version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    working_dir: '/app/'
    tty: true
    environment:
      TZ: "Asia/Tokyo"
    env_file:
      - .env.prod
    volumes:
      - ./backend/src:/app
      - ./logs/backend:/logs
