# Docker Compose (v2) 設定ファイル
# - version: の指定は不要 (v2 以降では無視されるため削除)
# - ネットワーク名は環境変数 NETWORK_NAME で一括管理

services:
  backend:
    # ビルド設定: backend/Dockerfile を使用
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: myapp_backend    # コンテナ名
    working_dir: /app                # 作業ディレクトリ
    tty: true                        # TTY 有効化
    env_file:
      - .env                         # ルートの .env を読み込む
    environment:
      - TZ=${TZ}                     # タイムゾーン (例: Asia/Tokyo)
      - PYTHONPYCACHEPREFIX=/dev/null  # __pycache__ 無効化
    volumes:
      - ./backend/src:/app           # ソースをマウント
      - ./logs/backend:/var/log/backend  # ログ出力先
    depends_on:
      - db                           # DB 起動後に起動
    networks:
      - default                      # デフォルトネットワークを使用
    restart: always                  # 常に再起動

  db:
    image: postgres:16               # PostgreSQL 16
    container_name: myapp_postgres   # コンテナ名
    restart: always                  # 再起動ポリシー
    env_file:
      - .env                         # .env から環境変数を読み込む
    environment:
      - POSTGRES_DB=${POSTGRES_DB}     # DB 名
      - POSTGRES_USER=${POSTGRES_USER} # ユーザー名
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # パスワード
      - TZ=${TZ}                       # タイムゾーン
    ports:
      - "${POSTGRES_PORT}:5432"      # ホスト:コンテナ ポートマッピング
    volumes:
      - pgdata:/var/lib/postgresql/data   # データ永続化ボリューム
      - ./logs/postgresql:/var/log/postgresql # ログ出力先
    networks:
      - default                        # デフォルトネットワーク

  nginx:
    image: nginx:latest              # 最新版 Nginx
    container_name: myapp_nginx      # コンテナ名
    env_file:
      - .env                         # .env を読み込む
    environment:
      - TZ=${TZ}                     # タイムゾーン設定
    ports:
      - "${NGINX_PORT}:80"          # ホスト:コンテナ ポート
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro  # テンプレート
      - ./logs/nginx:/var/log/nginx    # ログ出力先
    # 起動時に envsubst でポート変数を展開し、Nginx をフォアグラウンド実行
    command: >
      /bin/sh -c "envsubst '$$BACKEND_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - backend                       # backend 起動後に起動
    networks:
      - default                       # デフォルトネットワーク
    restart: always                  # 常に再起動

# 永続化用ボリューム定義
volumes:
  pgdata:
    driver: local

# デフォルトネットワーク定義
# 環境変数 NETWORK_NAME で実際の名前を指定 (例: myapp_net)
networks:
  default:
    name: ${NETWORK_NAME}
    driver: bridge
