version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    working_dir: '/app/'
    tty: true
    environment:
      TZ: "Asia/Tokyo"
    env_file:
      - .env.dev
    depends_on:
      - db
    volumes:
      - ./backend/src:/app
      - ./logs/backend:/var/log/backend
    networks:
      - internal_network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: fastapi
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - ./logs/postgresql:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - internal_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
