version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  concise:
    format: "%(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: concise

  timed_server_file:
    class: utils.custom_log_handler.CustomTimedRotatingFileHandler
    formatter: standard
    filename: /var/log/backend/server.log
    when: 'midnight'
    interval: 1
    backupCount: 7
    encoding: utf-8
    delay: true
    level: INFO

  timed_error_file:
    class: utils.custom_log_handler.CustomTimedRotatingFileHandler
    formatter: standard
    filename: /var/log/backend/error.log
    when: 'midnight'
    interval: 1
    backupCount: 7
    encoding: utf-8
    delay: true
    level: ERROR

  timed_debug_file:
    class: utils.custom_log_handler.CustomTimedRotatingFileHandler
    formatter: standard
    filename: /var/log/backend/debug.log
    when: 'midnight'
    interval: 1
    backupCount: 7
    encoding: utf-8
    delay: true
    level: DEBUG

loggers:
  uvicorn:
    handlers: [console, timed_server_file, timed_debug_file]
    level: DEBUG
    propagate: False

  uvicorn.access:
    handlers: [console, timed_server_file, timed_debug_file]
    level: DEBUG
    propagate: False

  uvicorn.error:
    handlers: [console, timed_error_file, timed_debug_file]
    level: ERROR
    propagate: False

root:
  handlers: [console, timed_debug_file]
  level: DEBUG
